global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']

  - job_name: 'rabbitmq-agent'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['agent:8080']
        labels:
          rabbitmq_cluster: "dev-cluster"

  - job_name: 'rabbitmq-publisher'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['publisher:8080']
        labels:
          rabbitmq_cluster: "dev-cluster"

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]